In [2]:
#załadowanie bibliotek

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

Wykonaj następujące polecenia:

1. załaduj dane z pliku `train.csv` do dataframe

In [3]:
df = pd.read_csv('train.csv') # wczytanie bazy danych
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

2. analogicznie do ćwiczeń z zajęć stwórz nowe zmienne wykonując następujące transformacje:

- `MSZoning` - one hot encoding 

In [4]:
MSZoning = np.array([df['MSZoning']],ndmin=2).transpose()
encoder = OneHotEncoder(sparse=False)
encoder.fit(MSZoning)
MSZ_OHE = encoder.transform(MSZoning)
print(MSZ_OHE, ',\n', encoder.categories_)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]] ,
 [array(['C (all)', 'FV', 'RH', 'RL', 'RM'], dtype=object)]


- `LotShape` - one hot encoding

In [5]:
LotShape = np.array([df['LotShape']],ndmin=2).transpose()
encoder = OneHotEncoder(sparse=False)
encoder.fit(LotShape)
LS_OHE = encoder.transform(LotShape)
print(LS_OHE, ',\n', encoder.categories_)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]] ,
 [array(['IR1', 'IR2', 'IR3', 'Reg'], dtype=object)]


- `LotArea` - skalowanie od 0 do 1

In [6]:
LotArea = np.array([df['LotArea']],ndmin=2).transpose()
scaler = MinMaxScaler()
scaler.fit(LotArea)
LA_scal = scaler.transform(LotArea)
print(scaler.data_min_, scaler.data_max_,',\n', LA_scal)

[1300.] [215245.] ,
 [[0.0334198 ]
 [0.03879502]
 [0.04650728]
 ...
 [0.03618687]
 [0.03934189]
 [0.04037019]]


- `OverallCond` - standaryzacja

In [7]:
OverallCond = np.array([df['OverallCond']],ndmin=2).transpose()
scaler = StandardScaler()
scaler.fit(OverallCond)
OC_scaler = scaler.transform(OverallCond)
print(OC_scaler)

[[-0.51719981]
 [ 2.17962776]
 [-0.51719981]
 ...
 [ 3.07857028]
 [ 0.38174271]
 [ 0.38174271]]


3. Utworzone nowe zmienne dołącz do istniejącego zbioru (dataframe'u z pkt 1), w nazwie nowych kolumn po one hot encoding umieść kategorię której odpowiada:     
Przykładowo dla zmiennej `LotShape` powstaną 4 nowe kolumny o nazwach: `'LotShape_IR1'`, `'LotShape_IR2'`, `'LotShape_IR3'`, `'LotShape_Reg'`. 

In [9]:
MSZ_df = pd.DataFrame(MSZ_OHE, columns=['MSZoning','MSZoning_FV','MSZoning_RH','MSZoning_RL','MSZoning_RM'])
LS_df = pd.DataFrame(LS_OHE, columns=['LotShape_IR1','LotShape_IR2','LotShape_IR3','LotShape_Reg'])
LA_df = pd.DataFrame(LA_scal, columns=['LotArea_scal'])
OC_df = pd.DataFrame(LA_scal, columns=['OC_scal'])
df2 = pd.concat([df, MSZ_df, LS_df, LA_df, OC_df], axis=1)

In [10]:
df2

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... MSZoning_FV MSZoning_RH MSZoning_RL  \
0            Lvl    AllPub  ...         0.0         0.0         1.0   
1            Lvl    AllPub  ...         0.0         0.0         1.0   
2            Lvl    AllPub  ...         0.0         0.0         1.0   
3            Lvl    AllPub  ...         0.0         0.0         1.0   
4            Lvl    AllPub  ...         0.0         0.0         1.0   
...          ...       ...  ...         ...         ...         ...   
1455         Lvl    AllPub  ...         0.0         0.0         1.0   
1456         Lvl    AllPub  ...         0.0         0.0         1.0   
1457         Lvl    AllPub  ...         0.0         0.0         1.0   
1458         Lvl    AllPub  ...         0.0         0.0         1.0   
1459         Lvl    AllPub  ...         0.0         0.0         1.0   

     MSZoning_RM LotShape_IR1 LotShape_IR2 LotShape_IR3  LotShape_Reg  \
0            0.0          0.0          0.0          0.0           1.0   
1            0.0          0.0          0.0          0.0           1.0   
2            0.0          1.0          0.0          0.0           0.0   
3            0.0          1.0          0.0          0.0           0.0   
4            0.0          1.0          0.0          0.0           0.0   
...          ...          ...          ...          ...           ...   
1455         0.0          0.0          0.0          0.0           1.0   
1456         0.0          0.0          0.0          0.0           1.0   
1457         0.0          0.0          0.0          0.0           1.0   
1458         0.0          0.0          0.0          0.0           1.0   
1459         0.0          0.0          0.0          0.0           1.0   

      LotArea_scal   OC_scal  
0         0.033420  0.033420  
1         0.038795  0.038795  
2         0.046507  0.046507  
3         0.038561  0.038561  
4         0.060576  0.060576  
...            ...       ...  
1455      0.030929  0.030929  
1456      0.055505  0.055505  
1457      0.036187  0.036187  
1458      0.039342  0.039342  
1459      0.040370  0.040370  

[1460 rows x 92 columns]